name: Manual Deploy (S & T Scripts)

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      run_s_script:
        description: 'Run S_refresh_supabase_working_version.py'
        required: false
        default: true
        type: boolean
      run_t_script:
        description: 'Run T_deploy_to_ai_models_main.py'
        required: false
        default: true
        type: boolean

jobs:
  manual-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write  # Allow writing to repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "SUPABASE_URL=https://atilxlecbaqcksnrgzav.supabase.co" >> .env
        echo "SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aWx4bGVjYmFxY2tzbnJnemF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTY5MTYsImV4cCI6MjA2Nzk3MjkxNn0.sYRFyQIEzZMlgg5RtHTXDSpvxl-KrJ8E7U3_UroIJog" >> .env

    - name: Run S_refresh_supabase_working_version.py
      if: ${{ inputs.run_s_script == true }}
      run: |
        echo "🔄 Running S_refresh_supabase_working_version.py..."
        python -u S_refresh_supabase_working_version.py

    - name: Run T_deploy_to_ai_models_main.py
      if: ${{ inputs.run_t_script == true }}
      run: |
        echo "🚀 Running T_deploy_to_ai_models_main.py..."
        python -u T_deploy_to_ai_models_main.py

    - name: Upload deployment logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: deployment-logs
        path: |
          *.log
          *-deployment-*.txt
          S-*.txt
          T-*.txt
        retention-days: 7

    - name: Show completion summary
      if: success()
      run: |
        echo "✅ Manual deployment completed successfully"
        echo "S script run: ${{ inputs.run_s_script }}"
        echo "T script run: ${{ inputs.run_t_script }}"
        echo "Check deployment logs artifact for detailed output"