name: Groq Pipeline Deployment (Manual)

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      script_choice:
        description: 'Choose which script to run (mutually exclusive)'
        required: true
        default: 'none'
        type: choice
        options:
        - 'none'
        - 'compare_with_supabase'
        - 'refresh_working_version'
        - 'deploy_to_main'

jobs:
  groq-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write  # Allow writing to repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      working-directory: groq_pipeline
      run: |
        python -m pip install --upgrade pip
        pip install requests supabase python-dotenv

    - name: Set environment variables
      working-directory: groq_pipeline
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        echo "✅ Environment variables set from GitHub secrets"

    - name: Show execution plan
      run: |
        echo "🎯 Groq Pipeline Deployment Plan:"
        echo "Selected option: ${{ inputs.script_choice }}"
        if [[ "${{ inputs.script_choice }}" == "compare_with_supabase" ]]; then
          echo "Will execute: H_compare_pipeline_with_supabase.py (Compare Pipeline with Supabase)"
        elif [[ "${{ inputs.script_choice }}" == "refresh_working_version" ]]; then
          echo "Will execute: G_refresh_supabase_working_version.py (Refresh Working Version)"
        elif [[ "${{ inputs.script_choice }}" == "deploy_to_main" ]]; then
          echo "Will execute: I_deploy_to_ai_models_main.py (Deploy to Production)"
        else
          echo "No script will be executed (none selected)"
        fi

    - name: Run H_compare_pipeline_with_supabase.py
      if: ${{ inputs.script_choice == 'compare_with_supabase' }}
      working-directory: groq_pipeline
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        echo "🔍 Running H_compare_pipeline_with_supabase.py..."
        echo "⚠️  This will compare pipeline data with Supabase working_version table"
        python -u H_compare_pipeline_with_supabase.py

    - name: Run G_refresh_supabase_working_version.py
      if: ${{ inputs.script_choice == 'refresh_working_version' }}
      working-directory: groq_pipeline
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        echo "🔄 Running G_refresh_supabase_working_version.py..."
        echo "⚠️  This will refresh the Supabase working_version table with Groq pipeline data"
        python -u G_refresh_supabase_working_version.py

    - name: Run I_deploy_to_ai_models_main.py
      if: ${{ inputs.script_choice == 'deploy_to_main' }}
      working-directory: groq_pipeline
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        echo "🚀 Running I_deploy_to_ai_models_main.py..."
        echo "⚠️  This will deploy from working_version to the main ai_models table"
        python -u I_deploy_to_ai_models_main.py

    - name: Upload deployment logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: groq-deployment-logs
        path: |
          groq_pipeline/*.log
          groq_pipeline/*-deployment-*.txt
          groq_pipeline/G-*.txt
          groq_pipeline/I-*.txt
        retention-days: 7

    - name: Show completion summary
      if: success()
      run: |
        echo "✅ Groq pipeline deployment completed successfully"
        echo "Script executed: ${{ inputs.script_choice }}"
        if [[ "${{ inputs.script_choice }}" == "compare_with_supabase" ]]; then
          echo "✅ Pipeline vs Supabase comparison completed"
        elif [[ "${{ inputs.script_choice }}" == "refresh_working_version" ]]; then
          echo "✅ Working version table refreshed with Groq data"
        elif [[ "${{ inputs.script_choice }}" == "deploy_to_main" ]]; then
          echo "✅ Data deployed to main ai_models table"
        else
          echo "ℹ️  No script was executed"
        fi
        echo "Check deployment logs artifact for detailed output"

    - name: Show failure summary
      if: failure()
      run: |
        echo "❌ Groq pipeline deployment failed"
        echo "Script that failed: ${{ inputs.script_choice }}"
        echo "Check deployment logs artifact for error details"
        echo "🔍 Common issues:"
        echo "  - Missing or invalid Supabase credentials"
        echo "  - Database connection timeout"
        echo "  - Invalid data format in pipeline outputs"
        echo "  - Missing GROQ_API_KEY secret"