name: OpenRouter Pipeline (T & U Scripts)

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      script_choice:
        description: 'Choose which script to run (mutually exclusive)'
        required: true
        default: 'none'
        type: choice
        options:
        - 'none'
        - 'run_t'
        - 'run_u'

jobs:
  openrouter-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write  # Allow writing to repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      working-directory: openrouter_pipeline
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      working-directory: openrouter_pipeline
      run: |
        echo "SUPABASE_URL=https://atilxlecbaqcksnrgzav.supabase.co" >> .env
        echo "SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aWx4bGVjYmFxY2tzbnJnemF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTY5MTYsImV4cCI6MjA2Nzk3MjkxNn0.sYRFyQIEzZMlgg5RtHTXDSpvxl-KrJ8E7U3_UroIJog" >> .env

    - name: Show execution plan
      run: |
        echo "🎯 OpenRouter Pipeline Execution Plan:"
        echo "Selected option: ${{ inputs.script_choice }}"
        if [[ "${{ inputs.script_choice }}" == "run_t" ]]; then
          echo "Will execute: T_refresh_supabase_working_version.py (Refresh Working Version)"
        elif [[ "${{ inputs.script_choice }}" == "run_u" ]]; then
          echo "Will execute: U_deploy_to_ai_models_main.py (Deploy to Production)"
        else
          echo "No script will be executed (none selected)"
        fi

    - name: Run T_refresh_supabase_working_version.py
      if: ${{ inputs.script_choice == 'run_t' }}
      working-directory: openrouter_pipeline
      run: |
        echo "🔄 Running T_refresh_supabase_working_version.py..."
        echo "⚠️  This will refresh the Supabase working_version table with OpenRouter pipeline data"
        python -u 01_scripts/T_refresh_supabase_working_version.py

    - name: Run U_deploy_to_ai_models_main.py
      if: ${{ inputs.script_choice == 'run_u' }}
      working-directory: openrouter_pipeline
      run: |
        echo "🚀 Running U_deploy_to_ai_models_main.py..."
        echo "⚠️  This will deploy from working_version to the main ai_models table"
        python -u 01_scripts/U_deploy_to_ai_models_main.py

    - name: Upload deployment logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: openrouter-deployment-logs
        path: |
          openrouter_pipeline/02_outputs/*.log
          openrouter_pipeline/02_outputs/*-deployment-*.txt
          openrouter_pipeline/02_outputs/T-*.txt
          openrouter_pipeline/02_outputs/U-*.txt
        retention-days: 7

    - name: Show completion summary
      if: success()
      run: |
        echo "✅ OpenRouter pipeline deployment completed successfully"
        echo "Script executed: ${{ inputs.script_choice }}"
        if [[ "${{ inputs.script_choice }}" == "run_t" ]]; then
          echo "✅ Working version table refreshed with OpenRouter data"
        elif [[ "${{ inputs.script_choice }}" == "run_u" ]]; then
          echo "✅ Data deployed to main ai_models table"
        else
          echo "ℹ️  No script was executed"
        fi
        echo "Check deployment logs artifact for detailed output"

    - name: Show failure summary
      if: failure()
      run: |
        echo "❌ OpenRouter pipeline deployment failed"
        echo "Script that failed: ${{ inputs.script_choice }}"

        echo "Check deployment logs artifact for error details"
