name: OpenRouter Pipeline (A-S)

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'openrouter_pipeline/**.py'
      - 'openrouter_pipeline/requirements.txt'
      - '.github/workflows/**'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 3 hours max
    permissions:
      contents: write  # Allow writing to repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      working-directory: openrouter_pipeline
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run complete pipeline
      working-directory: openrouter_pipeline/01_scripts
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        PIPELINE_SUPABASE_URL: ${{ secrets.PIPELINE_SUPABASE_URL }}
        HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      run: |
        python Z_run_A_to_S.py --no-venv --auto-all

    - name: Upload pipeline report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pipeline-execution-report
        path: openrouter_pipeline/02_outputs/Z-pipeline-execution-report.txt
        retention-days: 30

    - name: Upload processed data
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: processed-data
        path: |
          openrouter_pipeline/02_outputs/*.json
          openrouter_pipeline/02_outputs/*-report.txt
          openrouter_pipeline/02_outputs/last-run.txt
          !**/node_modules/**
        retention-days: 7

    - name: Commit processed data to repository
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Add timestamp file to 02_outputs (scripts already write directly there)
        echo "Pipeline completed: $(date -u)" > openrouter_pipeline/02_outputs/last-run.txt
        echo "Workflow run: ${{ github.run_number }}" >> openrouter_pipeline/02_outputs/last-run.txt
        echo "Repository: ${{ github.repository }}" >> openrouter_pipeline/02_outputs/last-run.txt

        # Verify files exist in 02_outputs
        echo "📁 Files in 02_outputs directory:"
        ls -la openrouter_pipeline/02_outputs/ || echo "No files found"

        # Commit if there are changes
        git add openrouter_pipeline/02_outputs/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "OpenRouter pipeline output: Run #${{ github.run_number }} $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push origin main
          echo "✅ Processed data committed to repository"
        fi

    - name: Upload organized processed data
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: pipeline-outputs
        path: openrouter_pipeline/02_outputs/
        retention-days: 30

    # Google pipeline trigger removed - handle manually

    - name: Show failure summary
      if: failure()
      run: |
        echo "❌ Pipeline execution failed"
        echo "Check the pipeline report artifact for detailed error information"
        echo "The report contains:"
        echo "  - Specific script that failed"
        echo "  - Detailed error messages"
        echo "  - Stage-by-stage execution status"
        echo "  - Timing information"